### ISSUE TITLE
Changed Filepath - Nov 2020

### ISSUE THREAD

**Issue by heyerbobby** [albertotb/get-gfs#3]
Hi Alberto

Not sure if you are still supporting this, but if you are, there seems to have been a change to the ftp location. 

- the path **'https://nomads.ncep.noaa.gov:9090/dods'** no  longer seems to be valid. 
- However you can still get access to the real time server files through **'https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/'**

**Comment by albertotb** [comment]
Hi Bobby, thanks for letting me know. I'm not officially supporting this since I would like to make this scripts a little bit more professional. However I will update the URL so they at least work, just in case someone finds this useful. Thanks again!

PS: you are welcome to make a PR if you feel like it
